services:
  - type: web
    name: shareez
    runtime: node
    buildCommand: npm install --prefix server && npm install --include=dev --prefix client && npm run build --prefix client
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1
